name: Create Issue from Form Response

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Issue from Form Response
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.YOUR_GITHUB_PERSONAL_ACCESS_TOKEN }}
        run: |
          # Replace the content here with your logic to create issues based on form responses
          # For example, you can use GitHub API to create issues
          curl -X POST -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/<your-username>/<your-repo>/issues \
            -d '{"title":"Form Response","body":"Here is the form response content"}'
